# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleportAuditReport < Formula
  desc "Audit reporting CLI for a Teleport cluster (activity, requests, security, compliance)"
  homepage "https://github.com/tenaciousdlg/teleport-audit-report"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.0/teleport-audit-report_1.1.0_darwin_amd64.tar.gz"
      sha256 "fcc0ad8b6670e2eaec12683aee913633bda3bec4589eef817faf1c5a9bcfa1bd"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.0/teleport-audit-report_1.1.0_darwin_arm64.tar.gz"
      sha256 "66295309276b8b3e75858005e10695eeb804e0f3fb0771af7faf76a76d51a664"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.0/teleport-audit-report_1.1.0_linux_amd64.tar.gz"
      sha256 "d64a16587997956b734e3bcb7ff5433e8f624c0b682f8677a5f62326fb183978"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.0/teleport-audit-report_1.1.0_linux_arm64.tar.gz"
      sha256 "c1e981f76355219ddf9e02cf9c912be567768544dbe212ed0b50080a804b46a1"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/audit-report version")
  end
end
