# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleportAuditReport < Formula
  desc "Audit reporting CLI for a Teleport cluster (activity, requests, security, compliance)"
  homepage "https://github.com/tenaciousdlg/teleport-audit-report"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.7.0/teleport-audit-report_1.7.0_darwin_amd64.tar.gz"
      sha256 "e7b46fbd0d42a7ba9781baf5cffb4247ebab414e66ccb8660e35e7bc3d437771"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.7.0/teleport-audit-report_1.7.0_darwin_arm64.tar.gz"
      sha256 "350a792a8b978cbb4ed6c875e0d7f4225523945bf8d4e7b2e455911fe2752fd9"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.7.0/teleport-audit-report_1.7.0_linux_amd64.tar.gz"
      sha256 "76f5258cb539c1165f0065ef95e03d4c668d380d450f370de7f98e94946bb67d"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.7.0/teleport-audit-report_1.7.0_linux_arm64.tar.gz"
      sha256 "635162739d3c6cb2c47f47c7474f8aee9daea6aab8c3cc4eb595a35a9970e401"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/audit-report version")
  end
end
