# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleportAuditReport < Formula
  desc "Audit reporting CLI for a Teleport cluster (activity, requests, security, compliance)"
  homepage "https://github.com/tenaciousdlg/teleport-audit-report"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.1/teleport-audit-report_1.1.1_darwin_amd64.tar.gz"
      sha256 "c00a9de318206e7911c4105ebe79bf42650cba357bbdcb7ef0768e1b29d49a14"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.1/teleport-audit-report_1.1.1_darwin_arm64.tar.gz"
      sha256 "2313929a97c9ff6945073d8f72f047380fac3e8d476dcf3bd7cef4c786f4064c"

      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.1/teleport-audit-report_1.1.1_linux_amd64.tar.gz"
      sha256 "6250c8d3736754acc73c5a2012c251582b5d56ce9cebf541e7e519cbbd8404c5"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenaciousdlg/teleport-audit-report/releases/download/v1.1.1/teleport-audit-report_1.1.1_linux_arm64.tar.gz"
      sha256 "444efb195348dd7292bc9610ec626983a1515979fe48100a29d5388a8570e8ab"
      define_method(:install) do
        bin.install "audit-report"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/audit-report version")
  end
end
